### ISSUE TITLE
Question: Any way to add the item below "Open in a New Tab"?

### ISSUE THREAD

**Issue by rafaelgomesxyz** [Rob--W/bookmark-container-tab#4]
The position of the item at the end of the context menu isn't very nice, it would be better if it was positioned below "Open in a New Tab", just like in the regular context menus.

**Comment by rafaelgomesxyz** [comment]
Perhaps using `parentId` (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create)? We would only need to find out the id of the first item.

**Comment by Rob--W** [comment]
That is not possible through the extension API.

You can move the menu item as follows:

**Disclaimer: This is an advanced hidden feature of Firefox; use at your own risk.**

1. Go to your profile directory (see `about:support` for the location)
2. Create a directory "chrome" if it does not already exist.
3. Create a file "userChrome.css" if it does not already exist.
4. Append the following content:

```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
 /* Compat note: browser.xhtml = Firefox 73+, browser.xul = Firefox 72- */
@-moz-document url(chrome://browser/content/browser.xhtml),
               url(chrome://browser/content/browser.xul) {
    /* "Open in New Tab" menu item */
    #placesContext_open\:newtab ~ * {
        -moz-box-ordinal-group: 2;
    }
    /* Position after the "Open in New Tab", but before anything else. */
    #bookmark-menu-container_robwu_nl-menuitem-_bookmark-menu-item {
        -moz-box-ordinal-group: 1;
    }
}
```
5. Visit `about:config` and set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`.
6. Restart Firefox.

I successfully tested this with Firefox 63 and Firefox Nightly (65).
And Firefox 76 and Firefox Nightly (78)

This relies on the non-standard [`-moz-box-ordinal-group`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-box-ordinal-group) property. If this ever gets removed, other alternatives may be used, such as [`order`](https://developer.mozilla.org/en-US/docs/Web/CSS/order) (e.g. with display flex or grid). When I used standard flex / grid display on the menu (`#placesContext > arrowscrollbox > scrollbox > box`), menu separators became invisible, so I switched back to the non-standard `-moz-box-ordinal-group` property.

Changelog:
- In Firefox 69, the `toolkit.legacyUserProfileCustomizations.stylesheets` preference is required to make use of this. ([bug 1541233](https://bugzilla.mozilla.org/show_bug.cgi?id=1541233))
- In Firefox 73, `browser.xul` has been renamed to `browser.xhtml` ([bug 1601094](https://bugzilla.mozilla.org/show_bug.cgi?id=1601094))
